export const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg", //679 * 829.
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Nike Slim shirt2",
      slug: "nike-slim-shirt2",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 20,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Nike Slim pants",
      slug: "nike-slim-pants",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Adidas fit pants",
      slug: "adidas-fit-pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "High quality shirt",
    },
  ],
};
